SET(CMAKE_SYSTEM_NAME Linux)
#SET(CMAKE_C_COMPILER /opt/nec/ve/bin/ncc)
#SET(CMAKE_CXX_COMPILER /opt/nec/ve/bin/nc++)
#SET(CMAKE_Fortran_COMPILER /opt/nec/ve/bin/nfort)
SET(CMAKE_C_COMPILER /home/P1401/bin/ncc)
SET(CMAKE_CXX_COMPILER /home/P1401/bin/nc++)
SET(CMAKE_Fortran_COMPILER /home/P1401/bin/nfort)
#SET(CMAKE_Fortran_COMPILER /opt/nec/ve/bin/nfort-2.2.2)

#SET(CMAKE_C_FLAGS "-g -O2")
#SET(CMAKE_CXX_FLAGS "-g -O2")
#SET(CMAKE_Fortran_FLAGS "-g -O2")
SET(CMAKE_C_FLAGS "-O2 -g -lcblas -lblas_openmp -fopenmp"  CACHE STRING "")
SET(CMAKE_CXX_FLAGS "-O2 -g -lcblas -lblas_openmp -fopenmp" CACHE STRING "")
SET(CMAKE_Fortran_FLAGS "-O2 -g -llapack -lblas_openmp -fopenmp" CACHE STRING "")
#SET(CMAKE_C_FLAGS "-O0 -g -lcblas -lblas_openmp -fopenmp"  CACHE STRING "")
#SET(CMAKE_CXX_FLAGS "-O0 -g -lcblas -lblas_openmp -fopenmp" CACHE STRING "")
#SET(CMAKE_Fortran_FLAGS "-O0 -g -llapack -lblas_openmp -fopenmp" CACHE STRING "")

#SET(CMAKE_Fortran_MODDIR_FLAG "-module")

#SET(CMAKE_C_COMPILE_OPTIONS_PIC "-fPIC")
#SET(CMAKE_C_COMPILE_OPTIONS_PIE "-fPIC")
#SET(CMAKE_CXX_COMPILE_OPTIONS_PIC "-fPIC")
#SET(CMAKE_CXX_COMPILE_OPTIONS_PIE "-fPIC")
#SET(CMAKE_Fortran_COMPILE_OPTIONS_PIC "-fPIC")
#SET(CMAKE_Fortran_COMPILE_OPTIONS_PIE "-fPIC")
#
#SET(CMAKE_SHARED_LIBRARY_C_FLAGS "-fPIC")
#SET(CMAKE_SHARED_LIBRARY_CXX_FLAGS "-fPIC")
#SET(CMAKE_SHARED_LIBRARY_Fortran_FLAGS "-fPIC")

SET(BLAS_LIBRARIES /opt/nec/ve/nlc/2.0.0/lib/libblas_openmp.so)
SET(LAPACK_LIBRARIES /opt/nec/ve/nlc/2.0.0/lib/liblapack.so)
