cmake3 -DWITH_ELMERGUI:BOOL=FALSE -DWITH_OpenMP:BOOL=FALSE -DWITH_MPI:BOOL=FALSE -DWITH_Mumps:BOOL=FALSE -DCMAKE_TOOLCHAIN_FILE=../aurora-toolchain.cmake -DCMAKE_INSTALL_PREFIX=../install ../elmerfem
